replicaCount: 3
image:
  repository: quay.io/wire/cannon
  tag: 2.50.344
  pullPolicy: IfNotPresent
config:
  logLevel: Info
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
service:
  name: cannon
  internalPort: 8080
  externalPort: 8080
drainTimeout: 0