replicaCount: 3
image:
  repository: quay.io/wire/spar
  tag: 2.51.2
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
service:
  externalPort: 8080
  internalPort: 8080
config:
  cassandra:
    host: aws-cassandra
  richInfoLimit: 5000
  maxScimTokens: 0
  logLevel: Info