replicaCount: 3
image:
  repository: quay.io/wire/cargohold
  tag: 2.50.339
service:
  externalPort: 8080
  internalPort: 8080
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
config:
  logLevel: Info