apiVersion: v1
data:
  cannon.yaml: |
    cannon:
      host: 0.0.0.0
      port: {{ .Values.service.internalPort }}
      externalHostFile: /etc/wire/cannon/ip/ip.txt

    gundeck:
      host: gundeck
      port: 8080
kind: ConfigMap
metadata:
  name: cannon
