apiVersion: v1
kind: ConfigMap
metadata:
  name: "proxy"
data:
  proxy.yaml: |
    host: 0.0.0.0
    port: {{ .Values.service.internalPort }}
    httpPoolSize: 1000
    maxConns: 5000
    secretsConfig: /etc/wire/proxy/secrets/proxy.config
