dependencies:
#####################################################
## dependent (demo, non-persistent, non-HA) databases
#
# Note: why are these charts not part of the wire-server chart?
# These charts, in particular cassandra/elasticsearch
# cannot be part of the wire-server chart, because of the required ordering of
# 1. install databases, wait for them to be ready
# 2. run database migrations (done as a pre-install/pre-upgrade hook)
# 3. install wire-server
# I.e. migrations cannot run before databases are ready, so one cannot make them a pre-install/upgrade hook. Making them a post-install hook also doesn't work:
# Installing all charts in parallel means brig/galley/gundeck won't start up 
# since migrations did not yet run; but the migrations hook
# requires all pods to be in a 'Ready' state before starting (condition for post-install); this is impossible.
#####################################################
- name: redis-ephemeral
  version: "0.1.0"
  repository: "file://../redis-ephemeral"
  tags:
    - redis-ephemeral
    - databases-ephemeral
    - demo
- name: elasticsearch-ephemeral
  version: "0.1.0"
  repository: "file://../elasticsearch-ephemeral"
  tags:
    - elasticsearch-ephemeral
    - databases-ephemeral
    - demo
- name: cassandra-ephemeral
  version: "0.1.0"
  repository: "file://../cassandra-ephemeral"
  tags:
    - cassandra-ephemeral
    - databases-ephemeral
    - demo
