teamSettings:
  enabled: false
accountPages:
  enabled: false
tls:
  enabled: true
  # NOTE: enable to automate certificate issuing with  jetstack/cert-manager instead of
  #       providing your own via secrets.yaml
  useCertificateManager: false

# CHANGEME-PROD: required, if certificate manager is used; set to receive cert expiration
#                notice and other Letsencrypt related notification
certificate-manager:
  certmasterEmail:

# CHANGEME-PROD: These values are suggested for deployments on bare metal and
#                should be adjusted on a per installation basis
config:
  dns:
    https: nginz-https.example.com
    ssl: nginz-ssl.example.com
    webapp: webapp.example.com
    fakeS3: assets.example.com
    teamSettings: teams.example.com
    accountPages: account.example.com

service:
  s3:
    externalPort: 9000
    serviceName: minio-external
    externallyCreated: true
