apiVersion: v1
kind: ConfigMap
metadata:
  name: es-init-config
  labels:
    wireService: {{ template "fullname" . }}
    app: {{ template "fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
{{- if .Values.hook.enabled }}
  annotations:
    # when hook.enabled=true (default), this chart does not work standalone, but is intended as
    # either a 'post'-subchart to an elasticsearch chart or a 'pre'-subchart to wire-server
    # For the meaning of hooks, see https://docs.helm.sh/developing_charts/#hooks
    "helm.sh/hook": {{ .Values.hook.type }}-install,{{ .Values.hook.type }}-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- end }}
data:
  init.sh: |
    #!/usr/bin/env bash

    set -xe

    ES_DNS_NAME={{ required "missing elasticsearch-index.elasticsearch.host !" .Values.elasticsearch.host }}
    ES_PORT={{ .Values.elasticsearch.port }}
    ES_ADDRESS=$ES_DNS_NAME:$ES_PORT


    echo '\nApplying index templates\n'
    # directory location needs to match what is at es-init.yaml
    curl -sSf -XPUT $ES_ADDRESS/_template/{{ .Values.elasticsearch.index }} -H "Content-Type: application/json" --data-binary @/tmp/templates/directory.json

    echo '\nCreating index, unless it already exists\n'
    curl -sSf --head $ES_ADDRESS/{{ .Values.elasticsearch.index }} | { curl -XPUT $ES_ADDRESS/{{ .Values.elasticsearch.index }}; }

  directory.json: |
    {
        "template": "directory*",
        "settings": {
            "refresh_interval": "5s",
            "number_of_shards": 5,
            "number_of_replicas": 2
        },

        "mappings": {

            "user" : {
                "properties": {
                     "normalized" : { "type": "text",    "store": false },
                     "name"       : { "type": "keyword", "index": false },
                     "handle"     : { "type": "text"                    },
                     "accent_id"  : { "type": "byte",    "index": false },
                     "suspended"  : { "type": "integer"                 }
                 }
            }

        }
    }
