redis-ephemeral:
  usePassword: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false

  master:
    resources:
      limits:
        cpu: "1000m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
  slave:
    resources:
      limits:
        cpu: "1000m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
