---
- hosts: etcd
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - etcd-helpers

- name: Bootstrap cluster
  import_playbook: roles-external/kubespray/cluster.yml


- import_playbook: kubernetes_logging.yml
