####################################################
# minio
####################################################
#
# minio requires at least 2 datadirs (e.g. 2 servers x 1 disk each)
# operating docs: https://docs.minio.io/docs/minio-admin-complete-guide.html
#
- hosts: minio
  any_errors_fatal: true
  become: true
  gather_facts: true
  vars:
    minio_server_env_extra: "MINIO_BROWSER=off"
    layouts:
      # The first minio instance on this server.
      layout1:
        servicename: "minio-server1"
        minio_server_addr: ":9000"
        minio_server_datadirs: "/var/lib/minio-server1"
        minio_server_envfile: "/etc/default/minio-server1"
      # The second minio instance on this server.
      layout2:
        servicename: "minio-server2"
        minio_server_addr: ":9092"
        minio_server_datadirs: "/var/lib/minio-server2"
        minio_server_envfile: "/etc/default/minio-server2"
  roles:
    - role: ansible-minio
      layout: layout1
      tags:
        - minio
    - role: ansible-minio
      layout: layout2
      tags:
        - minio
