dependencies:
- name: fluent-bit
  version: 2.7.0
  repository: https://s3-eu-west-1.amazonaws.com/public.wire.com/charts-googlestorage-mirror
# Source: https://github.com/wireapp/charts/blob/master/stable/fluent-bit/README.md
# TODO: For further upgrades, move to https://github.com/fluent/helm-charts/tree/master/charts/fluent-bit
