# See defaults in https://github.com/helm/charts/tree/master/stable/fluent-bit
fluent-bit:
  backend:
    type: es
    es:
      host: elasticsearch-ephemeral
      port: 9200
      # Elastic Index Name
      index: kubernetes_cluster
      type: flb_type
      logstash_prefix: kubernetes_cluster
      replace_dots: "On"
      time_key: "@timestamp"
      # Optional username credential for Elastic X-Pack access
      http_user:
      # Password for user defined in HTTP_User
      http_passwd:
      # Optional TLS encryption to ElasticSearch instance
      tls: "off"
      tls_verify: "on"
      # TLS certificate for the Elastic (in PEM format). Use if tls=on and tls_verify=on.
      tls_ca: ""
      # TLS debugging levels = 1-4
      tls_debug: 1

