dependencies:
- name: cassandra
  version: 0.15.2
  # Published from https://github.com/wireapp/charts/blob/master/incubator/cassandra
  repository: https://s3-eu-west-1.amazonaws.com/public.wire.com/charts
  alias: cassandra-ephemeral
